version: '2'
services:
  nginx:
    image: nginx:1-alpine
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
     - "3000:3000"

  app:
    build: ./app
    ports:
     - "8080:8080"
    volumes:
     - ./app/bin:/code/bin
     - ./app/controllers:/code/controllers
     - ./app/services:/code/services
     - ./app/public:/code/public
     - ./app/routes:/code/routes
     - ./app/views:/code/views
     - ./app/app.js:/code/app.js
